export const ACA = {
  rooms: {
    20: [5, 6, 7],
    30: [8, 9, 10, 11, 12],
    40: [13, 14],
    10: [1, 2, 3, 4],
    50: [15],
  },
  lecturers: [
    { name: "Gago", surname: "Gagyan", speciality: "Java" },
    { name: "Avet", surname: "Badalyan", speciality: "UI/UX" },
    { name: "Eduard", surname: "Harutyunyan", speciality: "ReactJS" },
    { name: "Norayr", surname: "Hayrikyan", speciality: "Project Management" },
    { name: "Elen", surname: "Ghazaryan", speciality: "JavaScript" },
    { name: "Edgar", surname: "Khudoyan", speciality: "NodeJS" },
    { name: "Rafayel", surname: "Afrikyan", speciality: "CSS" },
    { name: "Hovhannes", surname: "Kocharyan", speciality: "ReactJS" },
    { name: "Sona", surname: "Shahgeldyan", speciality: "NodeJS" },
    { name: "Elmira", surname: "Avagyan", speciality: "JavaScript" },
    { name: "Vrezh", surname: "Oganesyan", speciality: "HTML" },
    { name: "Mher", surname: "Armenia", speciality: "Python" },
  ],
  faculties: {
    "Frontend Bootcamp": {
      syllabus: [{ JavaScript: 5 }, { HTML: 3 }, { CSS: 3 }, { ReactJS: 2 }],
      students: [
        { name: "Joe", surname: "Valod" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "Backend Bootcamp": {
      syllabus: [
        { Java: 5 },
        { Node: 5 },
        { Python: 3 },
        { "Project Management": 2 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "UI/IX Bootcamp": {
      syllabus: [
        { "UI/UX": 5 },
        { HTML: 5 },
        { CSS: 5 },
        { "Project Management": 2 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "Machine learning": {
      syllabus: [
        { Python: 5 },
        { Java: 3 },
        { CSS: 3 },
        { "Project Management": 2 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "Project Management": {
      syllabus: [
        { "UI/UX": 5 },
        { HTML: 3 },
        { CSS: 2 },
        { "Project Management": 7 }, 
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
  },
};
