import photo1 from "./../assets/lecturers/txa (1).jpg";
import photo2 from "./../assets/lecturers/txa (1).png";
import photo3 from "../assets/lecturers/txa(1).jpeg";
import photo4 from "../assets/lecturers/txa (5).jpg";
import photo5 from "../assets/lecturers/axjik1.jpg";
import photo6 from "../assets/lecturers/txa (2).jpg";
import photo7 from "../assets/lecturers/txa (3).jpg";
import photo8 from "../assets/lecturers/txa (4).jpg";
import photo9 from "../assets/lecturers/axjik2.jpg";
import photo10 from "../assets/lecturers/axjik4.jpg";
import photo11 from "../assets/lecturers/txa (7).jpg";
import photo12 from "../assets/lecturers/txa (8).jpg";

export const ACA = {
  rooms: {
    20: [5, 6, 7],
    30: [8, 9, 10, 11, 12],
    40: [13, 14],
    10: [1, 2, 3, 4],
    50: [15],
  },
  lecturers: [
    {
      name: "Gago",
      surname: "Gagyan",
      speciality: "Java",
      img: photo1,
    },
    {
      name: "Avet",
      surname: "Badalyan",
      speciality: "UI/UX",
      img: photo2,
    },
    {
      name: "Eduard",
      surname: "Harutyunyan",
      speciality: "ReactJS",
      img: photo3,
    },
    {
      name: "Norayr",
      surname: "Hayrikyan",
      speciality: "Project Management",
      img: photo4,
    },
    {
      name: "Elen",
      surname: "Ghazaryan",
      speciality: "JavaScript",
      img: photo5,
    },
    {
      name: "Edgar",
      surname: "Khudoyan",
      speciality: "NodeJS",
      img: photo6,
    },
    {
      name: "Rafayel",
      surname: "Afrikyan",
      speciality: "CSS",
      img: photo7,
    },
    {
      name: "Hovhannes",
      surname: "Kocharyan",
      speciality: "ReactJS",
      img: photo8,
    },
    {
      name: "Sona",
      surname: "Shahgeldyan",
      speciality: "NodeJS",
      img: photo9,
    },
    {
      name: "Elmira",
      surname: "Avagyan",
      speciality: "JavaScript",
      img: photo10,
    },
    {
      name: "Vrezh",
      surname: "Oganesyan",
      speciality: "HTML",
      img: photo11,
    },
    {
      name: "Mher",
      surname: "Armenia",
      speciality: "Python",
      img: photo12,
    },
  ],
  faculties: {
    "Frontend Bootcamp": {
      syllabus: [{ JavaScript: 5 }, { HTML: 3 }, { CSS: 3 }, { ReactJS: 2 }],
      students: [
        { name: "Joe", surname: "Valod" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "Backend Bootcamp": {
      syllabus: [
        { Java: 5 },
        { Node: 5 },
        { Python: 3 },
        { "Project Management": 2 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "UI/IX Bootcamp": {
      syllabus: [
        { "UI/UX": 5 },
        { HTML: 5 },
        { CSS: 5 },
        { "Project Management": 2 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "Machine learning": {
      syllabus: [
        { Python: 5 },
        { Java: 3 },
        { CSS: 3 },
        { "Project Management": 2 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
    "Project Management": {
      syllabus: [
        { "UI/UX": 5 },
        { HTML: 3 },
        { CSS: 2 },
        { "Project Management": 7 },
      ],
      students: [
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
        { name: "name", surname: "surname" },
      ],
    },
  },
};
